version: '3.8'

services:
  backend:
    container_name: overtakeai-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - backend/.env
    ports:
      - "5000:5000"
    networks:
      - app-network

  frontend:
    container_name: overtakeai-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - frontend/.env
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge