version: '3.8'

services:
  backend:
    container_name: overtakeai-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - backend/.env
    ports:
      - "3003:5000"
    networks:
      - app-network
    limits:
      cpus: '1.0'
      memory: 512M

  frontend:
    container_name: overtakeai-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - frontend/.env
    ports:
      - "3002:80"
    depends_on:
      - backend
    networks:
      - app-network
    limits:
      cpus: '0.5'
      memory: 256M

networks:
  app-network:
    driver: bridge